# Generated by Django 5.1.2 on 2024-10-27 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLocation',
            fields=[
                ('home_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('is_repair_facility', models.BooleanField()),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
            ],
            options={
                'verbose_name': 'Home Location',
                'verbose_name_plural': 'Home Locations',
                'db_table': 'Home_Location',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('cost_ph', models.FloatField()),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'db_table': 'Vehicle_Type',
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('is_defective', models.BooleanField()),
                ('is_rented', models.BooleanField()),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('home_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.homelocation')),
                ('vehicle_type_id', models.ForeignKey(db_column='vehicle_type_id', on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reserved_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField()),
                ('picked_from', models.ForeignKey(db_column='picked_from', on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.homelocation')),
                ('returned_to', models.ForeignKey(db_column='returned_to', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations_returned_to_set', to='all_models.homelocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.vehicles')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('report', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.vehicles')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='DefectiveVehicles',
            fields=[
                ('defective_vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('repaired_at', models.DateTimeField(blank=True, null=True)),
                ('reported_defective_at', models.DateTimeField(auto_now_add=True)),
                ('repair_location', models.ForeignKey(db_column='repair_location', on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.homelocation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.vehicles')),
            ],
            options={
                'verbose_name': 'Defective Vehicle',
                'verbose_name_plural': 'Defective Vehicles',
                'db_table': 'Defective_Vehicles',
            },
        ),
    ]
