# Generated by Django 5.1.2 on 2024-10-29 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='vehicle_type_id',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.vehicletype'),
        ),
    ]
