# Generated by Django 5.1.2 on 2024-10-29 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_models', '0002_remove_vehicles_vehicle_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='all_models.vehicletype'),
        ),
    ]
